# Generated by Django 2.0.2 on 2018-02-07 19:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180207_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 2, 7, 19, 16, 27, 986629, tzinfo=utc), verbose_name='date'),
        ),
    ]
