# Generated by Django 2.0.2 on 2018-02-07 19:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180207_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 2, 7, 19, 26, 30, 680671, tzinfo=utc), verbose_name='date'),
        ),
    ]
