# Generated by Django 2.0.2 on 2018-02-07 19:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180207_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dil_purchase_price_sport', models.CharField(max_length=256, verbose_name='dil purchase price sport')),
                ('discount_1', models.CharField(max_length=256, verbose_name='discount 1')),
                ('discount_2', models.CharField(max_length=256, verbose_name='discount 2')),
                ('extra_support', models.EmailField(max_length=254, verbose_name='extra support')),
                ('dealer_purchase_price', models.FloatField(verbose_name='dealer purchase price')),
                ('pdi', models.IntegerField(choices=[(5, 5), (7, 7), (9, 9)])),
                ('r_servis', models.IntegerField(choices=[(2, 2), (10, 10), (20, 20)])),
                ('painting', models.FloatField(verbose_name='painting')),
                ('air_condition', models.FloatField(verbose_name='air condition')),
                ('warranty', models.FloatField(verbose_name='warranty')),
                ('trade_in', models.FloatField(verbose_name='trade in')),
                ('chassis_no_trade_in', models.CharField(max_length=256, verbose_name='chassis no trade in')),
                ('jacket_and_presents', models.FloatField(verbose_name='jackets & Presents')),
                ('radio', models.FloatField(verbose_name='radio')),
                ('tachograph', models.FloatField(verbose_name='tachograph')),
                ('adaptation_rup', models.FloatField(verbose_name='adaptation RUP')),
                ('estimated_tender_costs', models.FloatField(verbose_name='estimated tender costs')),
                ('driver_training', models.FloatField(verbose_name='driver training')),
                ('other', models.CharField(max_length=256, verbose_name='other')),
                ('sales_price', models.FloatField(verbose_name='sales price')),
            ],
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='precalculation',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Calculation', verbose_name='calculation'),
        ),
    ]
